name: "Snyk Platform Scan Monitor"

on:
  workflow_dispatch:  
    branches:
    - master
  schedule:
  - cron: "0 0 * * *"

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Platform Scan'
    runs-on: ubuntu-latest
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       
    steps:
    # Checkout Code
    - name: Checkout Code
      uses: actions/checkout@master

    # Install and Authenticate to Snyk
    - name: Install Snyk & Authenticate
      run: |
         sudo npm install -g snyk
         sudo npm install -g snyk-to-html
         snyk auth ${SNYK_TOKEN}
         
    # Run Snyk Scans
    - name: Run Snyk
      run: |
         snyk monitor --remote-repo-url="goofGithubAction" --target-reference="$(git branch --show-current)" || true
         snyk iac report --remote-repo-url="goofGithubAction" --target-reference="$(git branch --show-current)" || true
         snyk container monitor snykschmidtty/goof:latest --remote-repo-url="goofGithubAction" --target-reference="$(git branch --show-current)" || true
